### ISSUE TITLE
Unable to launch Vivecraft v10

### ISSUE THREAD

**Issue by CaiganMythFang** [jrbudda/minecrift#16]
Trying to launch the new update (Vivecraft v10) and this is the error in the launcher log 

`[09:00:32 WARN]: Couldn't download https://libraries.minecraft.net/com/mtbs3d/minecrift/1.7.10-Vivecraft-jrbudda10/minecrift-1.7.10-Vivecraft-jrbudda10.jar for job 'Version & Libraries'
java.lang.RuntimeException: Server responded with 403
    at com.mojang.launcher.updater.download.ChecksummedDownloadable.download(ChecksummedDownloadable.java:97) ~[launcher.jar:1.6.61]
    at com.mojang.launcher.updater.download.DownloadJob.popAndDownload(DownloadJob.java:109) [launcher.jar:1.6.61]
    at com.mojang.launcher.updater.download.DownloadJob.access$000(DownloadJob.java:12) [launcher.jar:1.6.61]
    at com.mojang.launcher.updater.download.DownloadJob$1.run(DownloadJob.java:86) [launcher.jar:1.6.61]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_91]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]`

Tested both with and without Forge 1614 support, though it seems the error is its trying to download from the wrong location.

**Comment by Tyrindor** [comment]
http://pastebin.com/84V0bmYD

Same here.

**Comment by darthnaber** [comment]
http://pastebin.com/1Vk0PX3a

me too

**Comment by jrbudda** [comment]
aww dangit holdon

**Comment by darthnaber** [comment]
found the issue the jar name isnt the same as the name thats in the code i think

**Comment by darthnaber** [comment]
i repleaced the name of the jar in C:\Users\user\AppData\Roaming.minecraft\libraries\com\mtbs3d\minecrift\1.7.10-Vivecraft-jrbudda10
to minecrift-1.7.10-Vivecraft-jrbudda10.jar

**Comment by CaiganMythFang** [comment]
Yep, confirming that changing the name of that file fixes the issue.

**Comment by Tyrindor** [comment]
Confirming that renaming fixed it and that v10 works with forge. I loaded up Infinity Evolved with 180 mods without issue.

Jrbudda, much love. Hopefully you maintain this when 1.8/1.9 minecrift comes out!

**Comment by jrbudda** [comment]
fixed it, turns out you CANT change the name in the code have to change the file name. Fun.
