### ISSUE TITLE
Can't get v26 to work

### ISSUE THREAD

**Issue by Joviangod** [jrbudda/minecrift#180]
Everything has been working great with each update but now at v26 my launcher wont launch any more! It loads a white screen for a few seconds then crashes back to the play button screen.

I get this crash report:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/9/16 12:04 PM
Description: Registering texture

java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferByte.<init>(Unknown Source)
    at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
    at java.awt.image.Raster.createWritableRaster(Unknown Source)
    at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
    at javax.imageio.ImageReader.getDestination(Unknown Source)
    at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
    at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at bpz.b(TextureMap.java:200)
    at bpz.a(TextureMap.java:136)
    at bqf.a(TextureManager.java:94)
    at bqf.a(TextureManager.java:76)
    at bqf.a(TextureManager.java:63)
    at bao.ag(Minecraft.java:888)
    at bao.f(Minecraft.java:1316)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jrbudda** [comment]
java.lang.OutOfMemoryError: Java heap space

out of memory loading a texture. Does regular minecraft work?

**Comment by Joviangod** [comment]
Yes, I tried running regular Minecraft and everything seemed fine.

**Comment by Techjar** [comment]
Can you pastebin the full crash report? It contains some important info for
this.

**Comment by Joviangod** [comment]
I hope this is what you're looking for:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/9/16 12:24 PM
Description: Registering texture

java.lang.OutOfMemoryError: Java heap space
    at java.awt.image.DataBufferByte.<init>(Unknown Source)
    at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
    at java.awt.image.Raster.createWritableRaster(Unknown Source)
    at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
    at javax.imageio.ImageReader.getDestination(Unknown Source)
    at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
    at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at bpz.b(TextureMap.java:200)
    at bpz.a(TextureMap.java:136)
    at bqf.a(TextureManager.java:94)
    at bqf.a(TextureManager.java:76)
    at bqf.a(TextureManager.java:63)
    at bao.ag(Minecraft.java:888)
    at bao.f(Minecraft.java:1316)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.awt.image.DataBufferByte.<init>(Unknown Source)
    at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
    at java.awt.image.Raster.createWritableRaster(Unknown Source)
    at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
    at javax.imageio.ImageReader.getDestination(Unknown Source)
    at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
    at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at javax.imageio.ImageIO.read(Unknown Source)
    at bpz.b(TextureMap.java:200)
    at bpz.a(TextureMap.java:136)

-- Resource location being registered --
Details:
    Resource location: minecraft:textures/atlas/blocks.png
    Texture object class: bpz
Stacktrace:
    at bqf.a(TextureManager.java:94)
    at bqf.a(TextureManager.java:76)
    at bqf.a(TextureManager.java:63)
    at bao.ag(Minecraft.java:888)

-- Initialization --
Details:
Stacktrace:
    at bao.f(Minecraft.java:1316)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 8225832 bytes (7 MB) / 2120679424 bytes (2022 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: vivecraft-1.7.10-Vivecraft-jrbudda26
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 364.72, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: [Sphax PureBDcraft 512x MC17.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (16)
OptiFine Version: OptiFine_1.7.10_HD_U_D1
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 16
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 364.72
OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4
```

**Comment by Techjar** [comment]
What the hell? Out of memory with only 7MB used? That makes no sense. Try
adding - Xmx512M to the launch arguments.

**Comment by Techjar** [comment]
Oops I meant -Xms512M

**Comment by jrbudda** [comment]
[Sphax PureBDcraft 512x MC17.zip]

try without the uberpack.

**Comment by Joviangod** [comment]
I ended up removing Sphax and it loaded. I only tested it for a moment and it crashed while I was swiping the trackpad on my inventory hand but I'll look it again tomorrow when I have time.

Thanks so much for responding so quickly everyone!

Also jrbudda, you are amazing, thanks for making this mod possible!
