### ISSUE TITLE
v27 crashing

### ISSUE THREAD

**Issue by MochiVR** [jrbudda/minecrift#181]
When I try to load a world with v27 game crashes. Here's my crash report

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 09/07/16 1:52 PM
Description: Starting integrated server

java.lang.InternalError: Malformed class name
    at java.lang.Class.getSimpleName(Class.java:1322)
    at java.lang.Class.isAnonymousClass(Class.java:1403)
    at com.google.gson.internal.Excluder.isAnonymousOrLocal(Excluder.java:216)
    at com.google.gson.internal.Excluder.excludeClass(Excluder.java:201)
    at com.google.gson.internal.Excluder.create(Excluder.java:113)
    at com.google.gson.Gson.getAdapter(Gson.java:356)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
    at com.google.gson.Gson.getAdapter(Gson.java:356)
    at com.google.gson.Gson.fromJson(Gson.java:802)
    at com.google.gson.Gson.fromJson(Gson.java:768)
    at ns.b(PlayerProfileCache.java:232)
    at ns.<init>(PlayerProfileCache.java:75)
    at net.minecraft.server.MinecraftServer.<init>(SourceFile:114)
    at bsx.<init>(IntegratedServer.java:43)
    at bao.a(Minecraft.java:2889)
    at bdx.e(SourceFile:162)
    at bdx.a(SourceFile:127)
    at bdw.a(GuiScreen.java:301)
    at bdw.k(GuiScreen.java:424)
    at bdw.p(GuiScreen.java:379)
    at bao.p(Minecraft.java:2359)
    at bao.ak(Minecraft.java:1493)
    at bao.f(Minecraft.java:1370)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.lang.Class.getSimpleName(Class.java:1322)
    at java.lang.Class.isAnonymousClass(Class.java:1403)
    at com.google.gson.internal.Excluder.isAnonymousOrLocal(Excluder.java:216)
    at com.google.gson.internal.Excluder.excludeClass(Excluder.java:201)
    at com.google.gson.internal.Excluder.create(Excluder.java:113)
    at com.google.gson.Gson.getAdapter(Gson.java:356)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
    at com.google.gson.Gson.getAdapter(Gson.java:356)
    at com.google.gson.Gson.fromJson(Gson.java:802)
    at com.google.gson.Gson.fromJson(Gson.java:768)
    at ns.b(PlayerProfileCache.java:232)
    at ns.<init>(PlayerProfileCache.java:75)
    at net.minecraft.server.MinecraftServer.<init>(SourceFile:114)
    at bsx.<init>(IntegratedServer.java:43)

-- Starting integrated server --
Details:
    Level ID: Vr world
    Level Name: Vr world
Stacktrace:
    at bao.a(Minecraft.java:2889)
    at bdx.e(SourceFile:162)
    at bdx.a(SourceFile:127)
    at bdw.a(GuiScreen.java:301)
    at bdw.k(GuiScreen.java:424)
    at bdw.p(GuiScreen.java:379)

-- Affected screen --
Details:
    Screen name: bee
Stacktrace:
    at bao.p(Minecraft.java:2359)
    at bao.ak(Minecraft.java:1493)
    at bao.f(Minecraft.java:1370)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 276539792 bytes (263 MB) / 337707008 bytes (322 MB) up to 4268163072 bytes (4070 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: vivecraft-1.7.10-Vivecraft-jrbudda27
    LWJGL: 2.9.1
    OpenGL: AMD Radeon (TM) R9 390 Series GL version 4.5.13440 Compatibility Profile Context 16.200.1013.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: [MassiveCraft-V9]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (16)
OptiFine Version: OptiFine_1.7.10_HD_U_D1
Render Distance Chunks: 9
Mipmaps: 4
Anisotropic Filtering: 16
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.13440 Compatibility Profile Context 16.200.1013.0
OpenGlRenderer: AMD Radeon (TM) R9 390 Series
OpenGlVendor: ATI Technologies Inc.
CpuCount: 4
```

**Comment by jrbudda** [comment]
uhhh... your crash is actually in the integrated server... something about a malformed player cache.  Your normal minecraft works... and version 26 of vivecraft works and you get this on 27?

**Comment by MochiVR** [comment]
Yeah, 10.2 works normally, and downgrading to 26 vivecraft works fine too

**Comment by Techjar** [comment]
Yeah this crash doesn't make any sense. It's not even happening in our code.

**Comment by Techjar** [comment]
Try turning off your resource pack.

**Comment by MochiVR** [comment]
ran a clean install of minecraft and it works fine now :) thanks for your awesome work and this amazing mod!

**Comment by Techjar** [comment]
Can you see what happens if you add back that MassiveCraft-V9 resource pack? I'm really curious, might have a lead to what's actually going on here.

**Comment by MochiVR** [comment]
no issues now with the v9 resource pack

**Comment by Techjar** [comment]
Huh... weird. I have no idea then. Well whatever, at least you fixed it.
