### ISSUE TITLE
Vivecraft crashes

### ISSUE THREAD

**Issue by Sauwercraud** [jrbudda/minecrift#185]
I can't get Vivecraft to run, as soon as I load or create a world it crashes:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/10/16 1:43 PM
Description: Starting integrated server

java.lang.InternalError: Malformed class name
    at java.lang.Class.getSimpleName(Class.java:1322)
    at java.lang.Class.isAnonymousClass(Class.java:1403)
    at com.google.gson.internal.Excluder.isAnonymousOrLocal(Excluder.java:216)
    at com.google.gson.internal.Excluder.excludeClass(Excluder.java:201)
    at com.google.gson.internal.Excluder.create(Excluder.java:113)
    at com.google.gson.Gson.getAdapter(Gson.java:356)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
    at com.google.gson.Gson.getAdapter(Gson.java:356)
    at com.google.gson.Gson.fromJson(Gson.java:802)
    at com.google.gson.Gson.fromJson(Gson.java:768)
    at ns.b(PlayerProfileCache.java:232)
    at ns.<init>(PlayerProfileCache.java:75)
    at net.minecraft.server.MinecraftServer.<init>(SourceFile:114)
    at bsx.<init>(IntegratedServer.java:43)
    at bao.a(Minecraft.java:2889)
    at bdx.e(SourceFile:162)
    at bdx.a(SourceFile:127)
    at bdw.a(GuiScreen.java:301)
    at bdw.k(GuiScreen.java:424)
    at bdw.p(GuiScreen.java:379)
    at bao.p(Minecraft.java:2359)
    at bao.ak(Minecraft.java:1493)
    at bao.f(Minecraft.java:1370)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.lang.Class.getSimpleName(Class.java:1322)
    at java.lang.Class.isAnonymousClass(Class.java:1403)
    at com.google.gson.internal.Excluder.isAnonymousOrLocal(Excluder.java:216)
    at com.google.gson.internal.Excluder.excludeClass(Excluder.java:201)
    at com.google.gson.internal.Excluder.create(Excluder.java:113)
    at com.google.gson.Gson.getAdapter(Gson.java:356)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
    at com.google.gson.Gson.getAdapter(Gson.java:356)
    at com.google.gson.Gson.fromJson(Gson.java:802)
    at com.google.gson.Gson.fromJson(Gson.java:768)
    at ns.b(PlayerProfileCache.java:232)
    at ns.<init>(PlayerProfileCache.java:75)
    at net.minecraft.server.MinecraftServer.<init>(SourceFile:114)
    at bsx.<init>(IntegratedServer.java:43)

-- Starting integrated server --
Details:
    Level ID: First Time
    Level Name: First Time
Stacktrace:
    at bao.a(Minecraft.java:2889)
    at bdx.e(SourceFile:162)
    at bdx.a(SourceFile:127)
    at bdw.a(GuiScreen.java:301)
    at bdw.k(GuiScreen.java:424)
    at bdw.p(GuiScreen.java:379)

-- Affected screen --
Details:
    Screen name: bee
Stacktrace:
    at bao.p(Minecraft.java:2359)
    at bao.ak(Minecraft.java:1493)
    at bao.f(Minecraft.java:1370)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 273291856 bytes (260 MB) / 330321920 bytes (315 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    Launched Version: vivecraft-1.7.10-Vivecraft-jrbudda27-shadersmod
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.39, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (16)
OptiFine Version: OptiFine_1.7.10_HD_U_D1
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 16
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.5.0 NVIDIA 368.39
OpenGlRenderer: GeForce GTX 980/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 12
```

**Comment by Techjar** [comment]
We don't actually know what's causing this. Probably something weird getting corrupted weirdly. Do a clean reinstall of Minecraft (delete .minecraft, backup saves if you want), that should fix it.

**Comment by Techjar** [comment]
Actually, try just deleting the usercache.json (upload it here first, I want to see it).

**Comment by Sauwercraud** [comment]
the usercache is pretty emtpy, Just gives out the UUID and my Name. Deleting did not help. Trying a reinstall now

**Comment by Techjar** [comment]
Huh, that's really weird. It's crashing in the code that loads that file, but I don't understand why.

**Comment by Sauwercraud** [comment]
It got fixed by deleting the .minecraft folder. Thank you Techjar!

**Comment by Techjar** [comment]
Cool, still don't know what's going on though! You're welcome!

**Comment by Techjar** [comment]
Marking as duplicate of #181 for reference.
