### ISSUE TITLE
Normal controls settings crash when it gets to "Jump"

### ISSUE THREAD

**Issue by GroxicTinch** [jrbudda/minecrift#191]
The error only occurs when using vivecraft rather then just forge, It seams to be because of the added "key_Rotate Free": "999", any reason why this is set to 999 and not just to 0 to disable it?

```
java.lang.ArrayIndexOutOfBoundsException: 999
    at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
    at net.minecraft.client.settings.GameSettings.func_74298_c(GameSettings.java:377)
    at net.minecraft.client.gui.GuiKeyBindingList$KeyEntry.func_148279_a(SourceFile:109)
    at net.minecraft.client.gui.GuiListExtended.func_148126_a(SourceFile:26)
    at net.minecraft.client.gui.GuiSlot.func_148120_b(GuiSlot.java:514)
    at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:381)
    at net.minecraft.client.gui.GuiControls.func_73863_a(SourceFile:107)
    at net.minecraft.client.renderer.EntityRenderer.drawFramebuffer(EntityRenderer.java:3930)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1531)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1372)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by jrbudda** [comment]
what version of vivecraft?

**Comment by GroxicTinch** [comment]
Latest Release, 28
That is unless the button was set to 999 previously and then has just propagated through since I never really had the need to go into original control settings.

**Comment by ravenx444** [comment]
Does this for me too, multiple versions.

**Comment by jrbudda** [comment]
likely due a bad value stuck in your saved options. maybe try resetting keybinds to default. Or editing your options.txt

**Comment by GroxicTinch** [comment]
Yea I had changed the value to 0 before I replied about what version but thought id say something because I didn't set it myself to cause the issue so it could be the default value or something which would be bad for other users not aware of how to change the options. (btw the change is needed in optionsViveProfiles.txt not options.txt)
