### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by BBleae** [jrbudda/minecrift#248]
I installed vivecraft 1.7.10 31r4 with forge10.13.4.1614.
There is a crash-report

[crash-2016-11-10_01.46.36-client.txt](https://github.com/jrbudda/minecrift/files/581673/crash-2016-11-10_01.46.36-client.txt)
`---- Minecraft Crash Report ----
// My bad.

Time: 16-11-10 上午1:46
Description: Initializing game

java.lang.UnsatisfiedLinkError: Unable to load library 'openvr_api': Native library (win32-x86-64/openvr_api.dll) not found in resource path ([file:/E:/VR/.minecraft/libraries/com/mtbs3d/minecrift/1.7.10-Vivecraft-jrbudda31r4/minecrift-1.7.10-Vivecraft-jrbudda31r4.jar, file:/E:/VR/.minecraft/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10.jar, file:/E:/VR/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar, file:/E:/VR/.minecraft/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar, file:/E:/VR/.minecraft/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar, file:/E:/VR/.minecraft/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar, file:/E:/VR/.minecraft/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar, file:/E:/VR/.minecraft/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar, file:/E:/VR/.minecraft/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar, file:/E:/VR/.minecraft/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar, file:/E:/VR/.minecraft/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar, file:/E:/VR/.minecraft/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar, file:/E:/VR/.minecraft/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar, file:/E:/VR/.minecraft/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar, file:/E:/VR/.minecraft/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar, file:/E:/VR/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar, file:/E:/VR/.minecraft/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar, file:/E:/VR/.minecraft/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar, file:/E:/VR/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar, file:/E:/VR/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar, file:/E:/VR/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar, file:/E:/VR/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar, file:/E:/VR/.minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar, file:/E:/VR/.minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar, file:/E:/VR/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar, file:/E:/VR/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar, file:/E:/VR/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar, file:/E:/VR/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar, file:/E:/VR/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar, file:/E:/VR/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar, file:/E:/VR/.minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar, file:/E:/VR/.minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar, file:/E:/VR/.minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar, file:/E:/VR/.minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar, file:/E:/VR/.minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar, file:/E:/VR/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar, file:/E:/VR/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar, file:/E:/VR/.minecraft/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar, file:/E:/VR/.minecraft/libraries/com/mojang/authlib/1.5.16/authlib-1.5.16.jar, file:/E:/VR/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar, file:/E:/VR/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar, file:/E:/VR/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.1/lwjgl-2.9.1.jar, file:/E:/VR/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.1/lwjgl_util-2.9.1.jar, file:/E:/VR/.minecraft/libraries/com/sun/jna/4.2.1/jna-4.2.1.jar, file:/E:/VR/.minecraft/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar, file:/E:/VR/.minecraft/libraries/org/json/json/20140107/json-20140107.jar, file:/E:/VR/.minecraft/libraries/de/fruitfly/ovr/JRift/0.8.0.0.1/JRift-0.8.0.0.1.jar, file:/E:/VR/.minecraft/libraries/net/aib42/mumblelink/JMumble/1.11/JMumble-1.11.jar, file:/E:/VR/.minecraft/libraries/optifine/OptiFine/1.7.10_HD_U_D1/OptiFine-1.7.10_HD_U_D1.jar, file:/E:/VR/.minecraft/versions/1.7.10/1.7.10.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:342)
	at jopenvr.JOpenVRLibrary.<clinit>(JOpenVRLibrary.java:17)
	at com.mtbs3d.minecrift.provider.MCOpenVR.init(MCOpenVR.java:283)
	at net.minecraft.client.Minecraft.initMinecrift(Minecraft.java:4577)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:833)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1352)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:342)
	at jopenvr.JOpenVRLibrary.<clinit>(JOpenVRLibrary.java:17)
	at com.mtbs3d.minecrift.provider.MCOpenVR.init(MCOpenVR.java:283)
	at net.minecraft.client.Minecraft.initMinecrift(Minecraft.java:4577)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:833)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1352)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 117531592 bytes (112 MB) / 306184192 bytes (292 MB) up to 1879048192 bytes (1792 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1792m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D1 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 8670D'
	Launched Version: HMCL 2.5.3.88
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8670D GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)
	OptiFine Version: OptiFine_1.7.10_HD_U_D1
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 8670D
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4`

**Comment by Techjar** [comment]
Vivecraft is not installed properly, as the openvr_api.dll is missing. It should be located in `.minecraft\win32`.

**Comment by BBleae** [comment]
@Techjar But the openvr_api.dll is already located in .minecraft\win32 and .minecraft\win64

**Comment by Techjar** [comment]
Are you using the normal launcher or some other one?

**Comment by DeeEmm** [comment]
I have same issue running on OSX

**Comment by Techjar** [comment]
OSX isn't something we officially support or have tested, so I have no idea if it works at all.
