### ISSUE TITLE
Oculus Touch 1.7.10 Control Issues

### ISSUE THREAD

**Issue by AdamLadell** [jrbudda/minecrift#261]
Hi,

I am trying to run ViveCraft on Minecraft 1.7.10 with my Oculus + Touch. The game's controls are different to 1.11 for some reason. On top of that, if I go into the VR Settings => Controls menu it doesn't present the options to assign actions to the analogue sticks (I can assign for pressing it, just not left, right, up, down)

Any help would be greatly appreciated!

Thanks,

Adam

**Comment by jrbudda** [comment]
Yup those changes haven't made it into the 1.7.10 branch just yet. Hopefully today.

**Comment by AdamLadell** [comment]
Nice!

Thanks for the fast response!

**Comment by AdamLadell** [comment]
Any update on when this'll be available?

**Comment by jrbudda** [comment]
Soon(tm)

**Comment by jrbudda** [comment]
[removed]

**Comment by jrbudda** [comment]
wait this one is better

[vivecraft-1.7.10-Vivecraft-jrbudda34-installer.exe.zip](https://github.com/jrbudda/minecrift/files/665407/vivecraft-1.7.10-Vivecraft-jrbudda34-installer.exe.zip)

**Comment by AdamLadell** [comment]
Hi, I tried it out but I am getting this error when trying to start a world.

<details> 
  <summary>Error</summary>
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 12/22/16 8:45 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateSwingAttack(OpenVRPlayer.java:995)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.onLivingUpdate(OpenVRPlayer.java:188)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:373)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(EntityClientPlayerMP.java:156)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1510)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1382)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.updateSwingAttack(OpenVRPlayer.java:995)
	at com.mtbs3d.minecrift.provider.OpenVRPlayer.onLivingUpdate(OpenVRPlayer.java:188)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:373)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(EntityClientPlayerMP.java:156)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityClientPlayerMP)
	Entity ID: 237
	Entity Name: AdamLadell
	Entity's Exact location: -18.50, 73.62, 263.50
	Entity's Block location: World: (-19,73,263), Chunk: (at 13,4,7 in -2,16; contains blocks -32,0,256 to -17,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['AdamLadell'/237, l='MpServer', x=-18.50, y=73.62, z=263.50]]
	Chunk stats: MultiplayerChunkCache: 45, 54
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-28,64,256), Chunk: (at 4,4,0 in -2,16; contains blocks -32,0,256 to -17,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 22 game time, 22 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 37 total; [EntitySpider['Spider'/256, l='MpServer', x=-25.50, y=27.00, z=270.50], EntitySkeleton['Skeleton'/257, l='MpServer', x=-35.50, y=23.00, z=303.50], EntityBat['Bat'/149, l='MpServer', x=-43.26, y=25.00, z=221.43], EntityItem['item.tile.torch'/150, l='MpServer', x=-35.78, y=25.13, z=223.59], EntitySkeleton['Skeleton'/151, l='MpServer', x=-38.50, y=26.00, z=234.50], EntitySkeleton['Skeleton'/152, l='MpServer', x=-42.50, y=26.00, z=233.44], EntitySkeleton['Skeleton'/153, l='MpServer', x=-42.50, y=26.00, z=230.50], EntitySpider['Spider'/154, l='MpServer', x=-42.50, y=26.00, z=227.50], EntityMinecartChest['entity.MinecartChest.name'/155, l='MpServer', x=-37.50, y=23.50, z=288.50], EntitySpider['Spider'/156, l='MpServer', x=-46.50, y=19.00, z=290.50], EntityMinecartChest['entity.MinecartChest.name'/157, l='MpServer', x=-35.50, y=23.50, z=305.50], EntityMinecartChest['entity.MinecartChest.name'/161, l='MpServer', x=-26.50, y=27.50, z=235.50], EntityItem['item.tile.rail'/162, l='MpServer', x=-24.85, y=27.13, z=247.99], EntityItem['item.tile.rail'/163, l='MpServer', x=-25.31, y=27.13, z=249.16], EntityCow['Cow'/164, l='MpServer', x=-29.50, y=69.00, z=280.50], EntityCow['Cow'/165, l='MpServer', x=-25.47, y=69.00, z=281.50], EntityCow['Cow'/166, l='MpServer', x=-26.91, y=69.00, z=281.50], EntityCow['Cow'/167, l='MpServer', x=-28.22, y=69.00, z=281.50], EntityZombie['Zombie'/296, l='MpServer', x=-24.50, y=27.00, z=272.50], EntityZombie['Zombie'/299, l='MpServer', x=-20.50, y=27.00, z=272.50], EntityZombie['Zombie'/303, l='MpServer', x=-74.50, y=29.00, z=266.50], EntityMinecartChest['entity.MinecartChest.name'/177, l='MpServer', x=3.50, y=26.50, z=257.50], EntityWolf['Wolf'/178, l='MpServer', x=11.50, y=75.00, z=302.50], EntityWolf['Wolf'/179, l='MpServer', x=11.50, y=74.00, z=300.50], EntityWolf['Wolf'/180, l='MpServer', x=8.50, y=75.00, z=307.50], EntitySpider['Spider'/245, l='MpServer', x=-36.50, y=23.00, z=296.50], EntityWolf['Wolf'/181, l='MpServer', x=8.50, y=75.00, z=306.50], EntitySlime['Slime'/246, l='MpServer', x=-53.50, y=29.00, z=226.50], EntityMinecartChest['entity.MinecartChest.name'/120, l='MpServer', x=-79.50, y=23.50, z=219.50], EntityMinecartChest['entity.MinecartChest.name'/121, l='MpServer', x=-77.50, y=23.50, z=247.50], EntityClientPlayerMP['AdamLadell'/237, l='MpServer', x=-18.50, y=73.62, z=263.50], EntityEnderman['Enderman'/122, l='MpServer', x=-77.50, y=23.00, z=242.50], EntityZombie['Zombie'/123, l='MpServer', x=-77.50, y=23.00, z=252.50], EntityZombie['Zombie'/124, l='MpServer', x=-78.50, y=23.00, z=248.50], EntityZombie['Zombie'/125, l='MpServer', x=-68.50, y=60.00, z=242.50], EntityItem['item.tile.torch'/126, l='MpServer', x=-76.44, y=21.13, z=261.25], EntityItem['item.tile.torch'/127, l='MpServer', x=-69.25, y=16.13, z=301.84]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:3498)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1404)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 179266072 bytes (170 MB) / 462114816 bytes (440 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D1 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.33' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Launched Version: vivecraft-1.7.10-Vivecraft-jrbudda34-forge-shadersmod
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)
	OptiFine Version: OptiFine_1.7.10_HD_U_D1
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.0 NVIDIA 376.33
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
</details>

**Comment by jrbudda** [comment]
ah whoops, sorry, you're playing with Forge?

**Comment by AdamLadell** [comment]
Yeah

**Comment by jrbudda** [comment]
try dis one.

[vivecraft-1.7.10-Vivecraft-jrbudda34-installer.exe.zip](https://github.com/jrbudda/minecrift/files/667445/vivecraft-1.7.10-Vivecraft-jrbudda34-installer.exe.zip)

**Comment by AdamLadell** [comment]
Firstly, thanks so much for all your help so far! Awesome to see a developer that cares!

Secondly, I've run into another issue. I assigned the Y_Press action to press the 'Esc' key on the keyboard. However, when I press the Y key in game, it crashes (Haven't tested with any other option yet.) Here's the log.

<details>
<summary> Error </summary>
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 12/22/16 9:18 AM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot type character 
	at com.mtbs3d.minecrift.utils.KeyboardSimulator.getCodes(KeyboardSimulator.java:147)
	at com.mtbs3d.minecrift.utils.KeyboardSimulator.type(KeyboardSimulator.java:41)
	at com.mtbs3d.minecrift.control.VRControllerButtonMapping.press(VRControllerButtonMapping.java:41)
	at com.mtbs3d.minecrift.provider.MCOpenVR.processControllerButtonsOculus(MCOpenVR.java:1886)
	at com.mtbs3d.minecrift.provider.MCOpenVR.poll(MCOpenVR.java:610)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1557)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1382)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.mtbs3d.minecrift.utils.KeyboardSimulator.getCodes(KeyboardSimulator.java:147)
	at com.mtbs3d.minecrift.utils.KeyboardSimulator.type(KeyboardSimulator.java:41)
	at com.mtbs3d.minecrift.control.VRControllerButtonMapping.press(VRControllerButtonMapping.java:41)
	at com.mtbs3d.minecrift.provider.MCOpenVR.processControllerButtonsOculus(MCOpenVR.java:1886)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['AdamLadell'/323, l='MpServer', x=186.85, y=79.62, z=158.46]]
	Chunk stats: MultiplayerChunkCache: 65, 74
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (200,64,160), Chunk: (at 8,4,0 in 12,10; contains blocks 192,0,160 to 207,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1050 game time, 1050 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 52 total; [EntityCreeper['Creeper'/129, l='MpServer', x=174.50, y=31.00, z=108.50], EntityBat['Bat'/130, l='MpServer', x=172.61, y=24.80, z=108.45], EntityCreeper['Creeper'/131, l='MpServer', x=160.50, y=31.00, z=147.50], EntityZombie['Zombie'/132, l='MpServer', x=172.06, y=44.00, z=151.50], EntitySkeleton['Skeleton'/133, l='MpServer', x=172.50, y=44.00, z=146.50], EntityCreeper['Creeper'/134, l='MpServer', x=165.50, y=47.00, z=164.50], EntityZombie['Zombie'/135, l='MpServer', x=164.03, y=26.00, z=223.53], EntityCreeper['Creeper'/147, l='MpServer', x=191.50, y=31.00, z=108.50], EntityBat['Bat'/148, l='MpServer', x=183.80, y=54.77, z=104.09], EntityBat['Bat'/149, l='MpServer', x=189.00, y=31.10, z=123.63], EntityCreeper['Creeper'/150, l='MpServer', x=187.25, y=47.00, z=125.94], EntityCreeper['Creeper'/151, l='MpServer', x=187.66, y=47.00, z=126.91], EntityCreeper['Creeper'/152, l='MpServer', x=187.50, y=48.00, z=139.50], EntitySkeleton['Skeleton'/153, l='MpServer', x=187.50, y=18.00, z=151.50], EntityBat['Bat'/154, l='MpServer', x=187.66, y=21.10, z=157.75], EntityBat['Bat'/155, l='MpServer', x=188.11, y=16.80, z=162.16], EntitySkeleton['Skeleton'/163, l='MpServer', x=206.28, y=53.00, z=106.27], EntityZombie['Zombie'/164, l='MpServer', x=192.50, y=29.00, z=123.50], EntityBat['Bat'/165, l='MpServer', x=190.13, y=29.76, z=123.23], EntityEnderman['Enderman'/166, l='MpServer', x=193.07, y=45.00, z=114.13], EntitySkeleton['Skeleton'/167, l='MpServer', x=198.50, y=27.00, z=140.69], EntityCreeper['Creeper'/168, l='MpServer', x=203.50, y=30.00, z=153.50], EntitySkeleton['Skeleton'/169, l='MpServer', x=197.50, y=15.00, z=170.50], EntitySkeleton['Skeleton'/170, l='MpServer', x=199.13, y=16.00, z=169.66], EntityItem['item.tile.sand.default'/171, l='MpServer', x=199.88, y=77.13, z=167.88], EntityZombie['Zombie'/172, l='MpServer', x=206.09, y=25.00, z=193.38], EntitySkeleton['Skeleton'/182, l='MpServer', x=208.50, y=52.00, z=105.50], EntityCreeper['Creeper'/183, l='MpServer', x=212.63, y=47.00, z=114.00], EntityBat['Bat'/184, l='MpServer', x=218.75, y=28.10, z=139.25], EntityBat['Bat'/185, l='MpServer', x=220.31, y=27.52, z=144.87], EntityZombie['Zombie'/194, l='MpServer', x=229.50, y=30.00, z=138.50], EntityCreeper['Creeper'/195, l='MpServer', x=229.37, y=30.00, z=139.50], EntityZombie['Zombie'/196, l='MpServer', x=224.50, y=30.00, z=146.50], EntityClientPlayerMP['AdamLadell'/323, l='MpServer', x=186.85, y=79.62, z=158.46], EntityBat['Bat'/331, l='MpServer', x=197.29, y=13.00, z=184.07], EntityBat['Bat'/91, l='MpServer', x=128.87, y=46.17, z=128.43], EntityZombie['Zombie'/98, l='MpServer', x=131.72, y=56.00, z=109.78], EntitySkeleton['Skeleton'/99, l='MpServer', x=132.56, y=17.00, z=116.97], EntitySkeleton['Skeleton'/100, l='MpServer', x=134.50, y=18.00, z=121.50], EntitySkeleton['Skeleton'/101, l='MpServer', x=133.50, y=18.00, z=122.50], EntitySkeleton['Skeleton'/102, l='MpServer', x=133.50, y=32.00, z=123.50], EntityBat['Bat'/103, l='MpServer', x=127.81, y=23.93, z=139.52], EntityZombie['Zombie'/104, l='MpServer', x=129.50, y=53.00, z=139.50], EntityBat['Bat'/105, l='MpServer', x=143.97, y=28.66, z=148.66], EntityBat['Bat'/106, l='MpServer', x=130.25, y=24.59, z=144.66], EntityCreeper['Creeper'/107, l='MpServer', x=137.50, y=50.00, z=156.50], EntityZombie['Zombie'/108, l='MpServer', x=138.50, y=25.00, z=187.50], EntityPig['Pig'/120, l='MpServer', x=154.50, y=63.00, z=97.50], EntityPig['Pig'/121, l='MpServer', x=153.50, y=63.00, z=99.50], EntitySkeleton['Skeleton'/122, l='MpServer', x=147.50, y=31.00, z=135.50], EntityZombie['Zombie'/123, l='MpServer', x=146.50, y=21.00, z=164.50], EntitySkeleton['Skeleton'/124, l='MpServer', x=146.50, y=19.00, z=177.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:3498)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1411)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 213534768 bytes (203 MB) / 498851840 bytes (475 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D1 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.33' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Launched Version: vivecraft-1.7.10-Vivecraft-jrbudda34-forge-shadersmod
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)
	OptiFine Version: OptiFine_1.7.10_HD_U_D1
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 16
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.0 NVIDIA 376.33
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
</details>

**Comment by jrbudda** [comment]
yea dont do that, the Y key is already the menu. In fact don't bind anything to that as the menu is actually hard-coded.

**Comment by AdamLadell** [comment]
I tried using the Y key without binding anything, but it didn't seem to open the menu

**Comment by jrbudda** [comment]
well that's a separate problem then lol

**Comment by jrbudda** [comment]
maybe reset your control bindings, I dont see why it shouldnt work.

**Comment by AdamLadell** [comment]
Alright, I reset my keybindings in the VR Controls section (Normal keybindings were already the default so couldn't reset).

The Y key still doesn't seem to open the menu, however the Esc key on the keyboard does. 

(Keep in mind this is a COMPLETELY fresh install of Minecraft 1.7.10 with Forge, no additional mods are installed)

**Comment by jrbudda** [comment]
should do it
[vivecraft-1.7.10-Vivecraft-jrbudda34-installer.exe.zip](https://github.com/jrbudda/minecrift/files/667775/vivecraft-1.7.10-Vivecraft-jrbudda34-installer.exe.zip)

**Comment by AdamLadell** [comment]
That's working perfectly, however for some reason a sort of 'auto-jump' feature seems to be active. There is no option to turn this off in controls or VR Controls. Is there any chance of fixing this?

**Comment by jrbudda** [comment]
should be a setting called 'walk up blocks' in the locomotion settings.

**Comment by ShrikerChestTrees** [comment]
And now 2 Oculus (port of Iris).

**Comment by longlongCODE** [comment]
收到邮件了，但是如果邮件很重要还请你发一条短信通知我收信。号码18817566090    谢谢
