### ISSUE TITLE
incompatible with Random Things mod

### ISSUE THREAD

**Issue by BrianEdmonds** [jrbudda/minecrift#295]
This is a very early failure in startup, before the usual Forge startup screen even appears. I'm running vivecraft-1.12.2-jrbudda-6-alpha2. Here's the snippet from my local log:
```
[06:37:18] [main/INFO]: [STDOUT]: ************** Vivecraft critical error ***************
[06:37:18] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:121) ~[VivecraftMain.class:?]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117) ~[VivecraftMain.class:?]
	... 6 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/management/PlayerInteractionManager
	at Reflector.<clinit>(Reflector.java:244) ~[Reflector.class:?]
	at net.minecraft.init.Bootstrap.func_151353_a(Bootstrap.java:279) ~[ni.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:532) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:627) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(Main.java:129) ~[Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117) ~[VivecraftMain.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.management.PlayerInteractionManager
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at Reflector.<clinit>(Reflector.java:244) ~[Reflector.class:?]
	at net.minecraft.init.Bootstrap.func_151353_a(Bootstrap.java:279) ~[ni.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:532) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:627) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(Main.java:129) ~[Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117) ~[VivecraftMain.class:?]
	... 6 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer lumien.randomthings.asm.ClassTransformer@83e5898 from coremod LoadingPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[forge-1.12.2-14.23.1.2600.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at Reflector.<clinit>(Reflector.java:244) ~[Reflector.class:?]
	at net.minecraft.init.Bootstrap.func_151353_a(Bootstrap.java:279) ~[ni.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:532) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:627) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(Main.java:129) ~[Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117) ~[VivecraftMain.class:?]
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.SecurityException: class "aip"'s signer information does not match signer information of other classes in the same package
	at lumien.randomthings.asm.CustomClassWriter.getCommonSuperClass(CustomClassWriter.java:41) ~[CustomClassWriter.class:?]
	at org.objectweb.asm.ClassWriter.a(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at lumien.randomthings.asm.ClassTransformer.patchPlayerInteractionManager(ClassTransformer.java:668) ~[ClassTransformer.class:?]
	at lumien.randomthings.asm.ClassTransformer.transform(ClassTransformer.java:127) ~[ClassTransformer.class:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.1.2600.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at Reflector.<clinit>(Reflector.java:244) ~[Reflector.class:?]
	at net.minecraft.init.Bootstrap.func_151353_a(Bootstrap.java:279) ~[ni.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:532) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:627) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(Main.java:129) ~[Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117) ~[VivecraftMain.class:?]
	... 6 more
[06:37:18] [main/INFO]: [STDERR]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[06:37:18] [main/INFO]: [STDERR]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[06:37:18] [main/INFO]: [STDERR]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[06:37:18] [main/INFO]: [STDERR]: 	at java.lang.Runtime.exit(Runtime.java:107)
[06:37:18] [main/INFO]: [STDERR]: 	at java.lang.System.exit(System.java:968)
[06:37:18] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[06:37:18] [main/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

This is with RandomThings-MC1.12.2-4.1.2 in the just released 1.12.2 Forever Stranded Lost Souls modpack, though I had the same issue with Modern Skyblock 2. In that case I removed the mod, and it did not have a significant impact on the game, apart from a few placeholder items in loot chests. With Lost Souls it's locking up during world startup. (Might be unrelated, but this is an easy issue to report, so I'm starting here.)

**Comment by jrbudda** [comment]
Yea we're aware of this one and spent quite some time looking into it already. Haven't found a fix yet, will update if we find something.

**Comment by Techjar** [comment]
This has been fixed in recent v6 alphas
