### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [jrbudda/minecrift#299]
I start my game and it crash after 1 minute of loading.
My Crash Logs:

```
08:19:59 | launcher | Couldn't get hash for com/mtbs3d/minecrift/1.12.2-jrbudda-6-final-r3/minecrift-1.12.2-jrbudda-6-final-r3.jar from https://libraries.minecraft.net/com/mtbs3d/minecrift/1.12.2-jrbudda-6-final-r3/minecrift-1.12.2-jrbudda-6-final-r3.jar.sha1: HTTP 404: Not Found
-- | -- | --
08:19:59 | launcher | Have local file C:/Users\NiKunHax\AppData\Roaming\.minecraft\libraries\com/mtbs3d/minecrift/1.12.2-jrbudda-6-final-r3/minecrift-1.12.2-jrbudda-6-final-r3.jar but don't know what size or hash it should be. Have to assume it's good.
08:19:59 | launcher | Couldn't get hash for optifine/OptiFine/1.12.2_HD_U_C9/OptiFine-1.12.2_HD_U_C9.jar from https://libraries.minecraft.net/optifine/OptiFine/1.12.2_HD_U_C9/OptiFine-1.12.2_HD_U_C9.jar.sha1: HTTP 404: Not Found
08:19:59 | launcher | Have local file C:/Users\NiKunHax\AppData\Roaming\.minecraft\libraries\optifine/OptiFine/1.12.2_HD_U_C9/OptiFine-1.12.2_HD_U_C9.jar but don't know what size or hash it should be. Have to assume it's good.
08:19:59 | launcher | Couldn't get hash for 1.12.2 jar from https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar.sha1: HTTP 403: Forbidden
08:19:59 | launcher | Have local file C:/Users\NiKunHax\AppData\Roaming\.minecraft\versions\1.12.2/1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
08:20:01 | launcher | Couldn't get hash for com/sun/jna/4.2.1/jna-4.2.1.jar from http://vivecraft.org/jar/com/sun/jna/4.2.1/jna-4.2.1.jar.sha1: HTTP 404: Not Found
08:20:01 | launcher | Have local file C:/Users\NiKunHax\AppData\Roaming\.minecraft\libraries\com/sun/jna/4.2.1/jna-4.2.1.jar but don't know what size or hash it should be. Have to assume it's good.
08:20:02 | launcher | Couldn't get hash for de/fruitfly/ovr/JRift/0.8.0.0.1/JRift-0.8.0.0.1.jar from http://vivecraft.org/jar/de/fruitfly/ovr/JRift/0.8.0.0.1/JRift-0.8.0.0.1.jar.sha1: HTTP 404: Not Found
08:20:02 | launcher | Have local file C:/Users\NiKunHax\AppData\Roaming\.minecraft\libraries\de/fruitfly/ovr/JRift/0.8.0.0.1/JRift-0.8.0.0.1.jar but don't know what size or hash it should be. Have to assume it's good.
10:20:05 | game | OptiFineTweaker: acceptOptions OptiFineTweaker: injectIntoClassLoader OptiFine ClassTransformer OptiFine ZIP file: C:\Users\NiKunHax\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.12.2_HD_U_C9\OptiFine-1.12.2_HD_U_C9.jar   <log4j:Event logger="LaunchWrapper" timestamp="1523168405005" level="INFO" thread="main">     <log4j:Message><![CDATA[Calling tweak class com.mtbs3d.minecrift.tweaker.MinecriftVanillaTweaker]]></log4j:Message>   </log4j:Event>
10:20:05 | monitor | expected <
10:20:05 | game | MinecriftVanillaTweaker: acceptOptions MinecriftVanillaTweaker: injectIntoClassLoader Vivecraft ClassTransformer Vivecraft URL: file:/C:/Users/NiKunHax/AppData/Roaming/.minecraft/libraries/com/mtbs3d/minecrift/1.12.2-jrbudda-6-final-r3/minecrift-1.12.2-jrbudda-6-final-r3.jar Vivecraft ZIP file: C:\Users\NiKunHax\AppData\Roaming\.minecraft\libraries\com\mtbs3d\minecrift\1.12.2-jrbudda-6-final-r3\minecrift-1.12.2-jrbudda-6-final-r3.jar OptiFineTweaker: getLaunchArguments MinecriftVanillaTweaker: getLaunchArguments OptiFineTweaker: getLaunchTarget   <log4j:Event logger="LaunchWrapper" timestamp="1523168405020" level="INFO" thread="main">     <log4j:Message><![CDATA[Launching wrapped minecraft {net.minecraft.client.main.Main}]]></log4j:Message>   </log4j:Event>
10:20:05 | monitor | expected <
10:20:06 | game | Vivecraft: Overwrite bib bib (71351 != 112978) Vivecraft: Overwrite bud bud (20657 != 34145) Vivecraft: Overwrite bua bua (5324 != 5762) Vivecraft: Overwrite buc buc (936 != 4368) Vivecraft: Overwrite blk blk (15142 != 20454) Vivecraft: Overwrite blb blb (1671 != 1876) Vivecraft: Overwrite bkn bkn (3854 != 4180) Vivecraft: Overwrite blg blg (2909 != 5526) Vivecraft: Overwrite bkr bkr (3612 != 3846) Vivecraft: Overwrite bib$1 bib$1 (675 != 702) Patching class: bmg (net.minecraft.client.gui.inventory.GuiContainer) Patching method: a(IIF)V (drawScreen(IIF)V) Inserted colorMask calls Patching method: a(III)V (mouseClicked(III)V) Inserted pressShiftFake check Vivecraft: Overwrite bmb bmb (6238 != 6742) Vivecraft: Overwrite rl rl (6818 != 6933)   <log4j:Event logger="bib" timestamp="1523168406484" level="INFO" thread="main">     <log4j:Message><![CDATA[Setting user: NiKunHax]]></log4j:Message>   </log4j:Event>
10:20:06 | monitor | expected <
10:20:06 | game | Vivecraft: Overwrite ni ni (3796 != 6159)   <log4j:Event logger="no" timestamp="1523168406621" level="INFO" thread="main">     <log4j:Message><![CDATA[[STDOUT]: Vivecraft: Overwrite qf qf (35495 != 35608)]]></log4j:Message>   </log4j:Event>
10:20:06 | monitor | expected <
08:20:17 | cgb | Unable to load item model: 'minecraft:item/eatme_cake' for item: 'minecraft:eatme_cake'
08:20:17 | cgb | java.io.FileNotFoundException: minecraft:models/item/eatme_cake.json
08:20:17 | cgb | Unable to load item model: 'minecraft:item/drinkme_bottle' for item: 'minecraft:drinkme_bottle'
08:20:17 | cgb | java.io.FileNotFoundException: minecraft:models/item/drinkme_bottle.json
08:20:20 | cgb | Missing model for: minecraft:item/eatme_cake
08:20:20 | cgb | Missing model for: minecraft:item/drinkme_bottle
08:20:23 | chm | Author: Paul Lamb, www.paulscode.com
08:20:24 | cgb | Unable to load item model: 'minecraft:item/eatme_cake' for item: 'minecraft:eatme_cake'
08:20:24 | cgb | java.io.FileNotFoundException: minecraft:models/item/eatme_cake.json
08:20:24 | cgb | Unable to load item model: 'minecraft:item/drinkme_bottle' for item: 'minecraft:drinkme_bottle'
08:20:24 | cgb | java.io.FileNotFoundException: minecraft:models/item/drinkme_bottle.json
08:20:26 | cgb | Missing model for: minecraft:item/eatme_cake
08:20:26 | cgb | Missing model for: minecraft:item/drinkme_bottle
08:20:47 | bib | Failed to load any main menu world, falling back to old menu room
08:20:50 | bib | Unreported exception thrown! java.lang.NullPointerException
at bib.t(Minecraft.java:2540)
at bib.az(Minecraft.java:1590)
at bib.a(Minecraft.java:662)
at net.minecraft.client.main.Main.main(Main.java:129)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Techjar** [comment]
Please upload the full latest.log from .minecraft/logs

**Comment by ghost** [comment]
[crash-2018-04-08_00.35.54-client.txt](https://github.com/jrbudda/minecrift/files/1887580/crash-2018-04-08_00.35.54-client.txt)
[latest.log](https://github.com/jrbudda/minecrift/files/1887581/latest.log)
Here Crash and Logs

**Comment by ghost** [comment]
I tried to download vivecraft 1.12 but optifine were not found with an error similar to: Unable to download vivecraft.org/Optifine/optifine......
So i downloaded it from optifine.net

**Comment by Techjar** [comment]
Are you running this on a PC without an internet connection? While that's supposed to work fine, due to a missing null check it crashes until you run it with internet at least once (will be fixed in a future release). Alternatively, download this file and place it in `.minecraft/menuworlds`: https://cache.techjargaming.com/vivecraft/menuworlds/world0.mmw

If you're not running without an internet connection, then you need to look into why your Java is unable to make connections and download resources, otherwise you're going to be missing things and won't be able to play multiplayer. Make sure it's not blocked by your firewall (some firewalls may be overzealous and block Java by default, as it was used for malicious software in the plugin days).

**Comment by ghost** [comment]
I am playing with internet and i want to play multiplayer. What i have to do?

**Comment by Techjar** [comment]
Everything was explained in my previous comment. I don't have any idea why your Java can't connect to the internet, that's beyond the scope of our support. Sorry.
