### ISSUE TITLE
Vivecraft crash after Mojang screen: Couldn't toggle fullscreen org.lwjgl.LWJGLException: Failed to set display mode (-2).

### ISSUE THREAD

**Issue by r2hubert** [jrbudda/minecrift#323]
When starting vivecraft with Steam VR the client crash with this error:

[09:25:20] [main/ERROR]: Couldn't toggle fullscreen
org.lwjgl.LWJGLException: Failed to set display mode (-2).
at org.lwjgl.opengl.WindowsDisplay.nSwitchDisplayMode(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
at org.lwjgl.opengl.WindowsDisplay.switchDisplayMode(WindowsDisplay.java:358) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
at org.lwjgl.opengl.Display.switchDisplayMode(Display.java:359) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
at org.lwjgl.opengl.Display.setDisplayModeAndFullscreenInternal(Display.java:507) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
at org.lwjgl.opengl.Display.setFullscreen(Display.java:475) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
at net.minecraft.client.Minecraft.func_71352_k(Minecraft.java:2346) [bib.class:?]
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:920) [bib.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:636) [bib.class:?]
at net.minecraft.client.main.Main.main(Main.java:129) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117) [VivecraftMain.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: java.lang.IllegalStateException: Display not created
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at org.lwjgl.opengl.Display.update(Display.java:641)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at org.lwjgl.opengl.Display.update(Display.java:628)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at net.minecraft.client.Minecraft.setupRenderConfiguration(Minecraft.java:4599)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1558)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:656)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at net.minecraft.client.main.Main.main(Main.java:129)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at java.lang.reflect.Method.invoke(Method.java:497)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at com.mtbs3d.minecrift.main.VivecraftMain.main(VivecraftMain.java:117)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at java.lang.reflect.Method.invoke(Method.java:497)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[09:25:20] [main/INFO]: [net.minecraft.client.Minecraft:func_71411_J:1570]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:25:22] [main/FATAL]: Unreported exception thrown!

**Comment by Espergium** [comment]
Pastebin the crash log.

**Comment by r2hubert** [comment]
[crash-2018-12-17_17.35.21-client.txt](https://github.com/jrbudda/minecrift/files/2688595/crash-2018-12-17_17.35.21-client.txt)

**Comment by r2hubert** [comment]
Here is the full log.
[latest.log](https://github.com/jrbudda/minecrift/files/2688597/latest.log)

**Comment by r2hubert** [comment]
Found the issue. I have a mirror monitor as soon as I unplugged it the issue disappeared.

**Comment by Techjar** [comment]
Yeah that must be a bug in LWJGL when handling certain monitor layouts. Turning off fullscreen should also work.
