### ISSUE TITLE
Mixin apply failed for Eye Translucency Render Type?

### ISSUE THREAD

**Issue by Varrick1** [jrbudda/minecrift#349]
So, after adding and removing some additional mods (List below) I'm unexpectedly getting a new error when I check the logs. Minecraft itself throws this up as "Error Code: 1" in a pre-launch. It is in 1.19.2--

``[14Sep2022 19:14:45.777] [main/INFO] [org.vivecraft.tweaker.VivecraftTransformer/]: Vivecraft Replacing net.minecraft.client.renderer.culling.Frustum
[14Sep2022 19:14:45.785] [main/FATAL] [mixin/]: Mixin apply failed mixins.oculus.json:rendertype.MixinRenderType_FixEyesTranslucency -> net.minecraft.client.renderer.RenderType: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Redirect annotation on iris$fixEyesTranslucency could not find any targets matching 'm_173252_' in net.minecraft.client.renderer.RenderType. Using refmap oculus-refmap.json [PREINJECT Applicator Phase -> mixins.oculus.json:rendertype.MixinRenderType_FixEyesTranslucency -> Prepare Injections ->  -> redirect$zkg000$iris$fixEyesTranslucency()Lnet/minecraft/client/renderer/RenderStateShard$TransparencyStateShard; -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on iris$fixEyesTranslucency could not find any targets matching 'm_173252_' in net.minecraft.client.renderer.RenderType. Using refmap oculus-refmap.json [PREINJECT Applicator Phase -> mixins.oculus.json:rendertype.MixinRenderType_FixEyesTranslucency -> Prepare Injections ->  -> redirect$zkg000$iris$fixEyesTranslucency()Lnet/minecraft/client/renderer/RenderStateShard$TransparencyStateShard; -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.RedirectInjectionInfo.<init>(RedirectInjectionInfo.java:44) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:255) ~[OptiFine-1.19.2_HD_U_H9_LIB.jar%23323!/:?]
	at net.minecraft.CrashReport.m_127526_(CrashReport.java:175) ~[client-1.19.2-20220805.130853-srg.jar%23311!/:?]
	at net.minecraft.CrashReport.m_127529_(CrashReport.java:345) ~[client-1.19.2-20220805.130853-srg.jar%23311!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:144) ~[client-1.19.2-20220805.130853-srg.jar%23311!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23311!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.0.7.jar%2398!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2385!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2385!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2385!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2385!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2385!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2385!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2385!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
``

I looked far and wide for any solutions to what's going on, but I'm not the best at this sort of thing so I may be missing something quite simple. The mods I'm running (Although they don't seem to be impacting this error specifically) are

"angelring-1.19-2.1.3.jar"
"antighost-1.19.1-forge42.0.1-1.1.2.jar"
"appleskin-forge-mc1.19-2.4.2.jar"
"appliedenergistics2-12.2.0-beta.jar"
"aqcaracal-1.19.2-1.0-forge.jar"
"Aquaculture-1.19.2-2.4.6.jar"
"architectury-6.2.43-forge.jar"
"armorplus-1.19.2-19.1.0-beta.jar"
"ars_nouveau-1.19.1-3.2.10.jar"
"AttributeFix-Forge-1.19.2-17.1.2.jar"
"AutoRegLib-1.8-54.jar"
"auudio_forge_1.0.3_MC_1.19.jar"
"badpackets-forge-0.2.0.jar"
"bagofyurting-1.19.1-3.0.0.0.jar"
"balm-4.5.3.jar"
"betteranimalsplus-1.19-11.0.7-forge.jar"
"BetterCompatibilityChecker-1.0.7-build.35+mc1.19.2.jar"
"BHMenu-Forge-1.19.2-1.3.jar"
"blue_skies-1.19.2-1.3.20.jar"
"blueprint-1.19-6.0.6.jar"
"Bookshelf-Forge-1.19.2-16.1.5.jar"
"buildinggadgets-3.16.0-build.14+mc1.19.2.jar"
"bwncr-forge-1.19.2-3.14.0.jar"
"bygonenether-1.2.1-1.19.x.jar"
"caelus-forge-1.19.2-3.0.0.6.jar"
"Cataclysm-0.20-1.19.2-hotfix.jar"
"cfm-7.0.0-pre34-1.19.jar"
"ChanceCubes-1.19-5.0.2.466.jar"
"cherishedworlds-forge-6.0.1+1.19.2.jar"
"chunkloaders-1.2.2-forge-mc1.19.jar"
"citadel-1.12.7-1.19.jar"
"cloth-config-8.2.88-forge.jar"
"Clumps-forge-1.19.2-9.0.0+11.jar"
"CodeChickenLib-1.19.2-4.3.0.470-universal.jar"
"collective-1.19.2-4.52.jar"
"comforts-forge-6.0.0+1.19.2.jar"
"CommonCapabilities-1.19.2-2.8.3.jar"
"compact_storage_forge-5.0_lts_1.19.2b2.jar"
"compactmachines-5.1.0.jar"
"configured-1.5.8-1.19.jar"
"connectivity-1.19.1-3.3.jar"
"CosmeticArmorReworked-1.19.2-v1.jar"
"Craftable Horse Armour  Saddle-1.19-1.9.jar"
"craftingtweaks-forge-1.19-15.1.0.jar"
"CraftPresence-1.19.2-Release-1.8.11-universal.jar"
"Croptopia-1.19.2-FORGE-2.1.0.jar"
"Cucumber-1.19.2-6.0.1.jar"
"curios-forge-1.19.2-5.1.1.0.jar"
"Cyclic-1.19.2-1.7.9.jar"
"CyclopsCore-1.19.2-1.17.0.jar"
"DarkPaintings-Forge-1.19.2-13.1.2.jar"
"DarkUtilities-Forge-1.19.2-13.1.2.jar"
"Decorative Blocks-forge-1.19.2-3.0.0.jar"
"DefaultSettings-1.19.x-2.8.7.jar"
"domum_ornamentum-1.19-1.0.59-ALPHA-universal.jar"
"drippyloadingscreen_forge_1.6.4-1_MC_1.19.jar"
"duckling-2.0.7-forge.jar"
"dummmmmmy-1.19-1.5.5.jar"
"DungeonCrawl-1.19-2.3.11.jar"
"DungeonsArise-1.19-2.1.51-beta.jar"
"EarthMobs-1.19.2-3.0.0.jar"
"eatinganimation-1.19-3.1.0.jar"
"ecologics-forge-1.19.2-2.1.9.jar"
"elevatorid-1.19-1.8.7.jar"
"ellemes-container-library-2.1.0-alpha.9+1.19-forge.jar"
"enderchests-1.19-1.10.0.jar"
"endercrop-1.19.2-1.7.0-beta.jar"
"EnderStorage-1.19.2-2.10.1.181-universal.jar"
"endertanks-1.19-1.12.0.jar"
"engineersdecor-1.19.2-forge-1.3.26.jar"
"Enhanced_Celestials-forge-1.19-2.1.0.1.jar"
"entityculling-forge-1.5.2-mc1.19.1.jar"
"expandedstorage-8.1.0-alpha.2+1.19-forge.jar"
"ExplorersCompass-1.19.2-1.2.4-forge.jar"
"extragolems-19.2.2.jar"
"ExtremeReactors2-1.19-2.0.54.jar"
"extremesoundmuffler-3.32_forge-1.19.1.jar"
"fabric-api-0.60.0+1.19.2.jar"
"fancymenu_forge_2.12.1-1_MC_1.19-1.19.2.jar"
"FarmersDelight-1.19-1.1.2.jar"
"farmingforblockheads-forge-1.19-11.1.0.jar"
"FastLeafDecay-30.jar"
"ForgeEndertech-1.19.2-10.0.5.0-build.0599.jar"
"FramedBlocks-6.4.0.jar"
"friendsandfoes-forge-mc1.19.2-1.5.10.jar"
"geckolib-forge-1.19-3.1.19.jar"
"Gobber2-Forge-1.19.2-2.7.16.jar"
"goodall-1.1.0-forge.jar"
"gravestone-1.19.2-1.0.1.jar"
"guardvillagers-1.19.2-1.5.2.jar"
"HealthOverlay-1.19.2-7.1.1.jar"
"ImmersiveEngineering-1.19.2-9.0.0-153.jar"
"IMST_2_0_2.jar"
"IntegratedDynamics-1.19.2-1.11.10.jar"
"IntegratedTunnels-1.19.2-1.8.15.jar"
"ironfurnaces-1.19.2-3.6.1.jar"
"IronJetpacks-1.19.1-6.0.0.jar"
"itemcollectors-1.1.5b-forge-mc1.19.jar"
"Jade-1.19.1-forge-8.1.1.jar"
"JAOPCA-1.19.2-4.2.0.1.jar"
"justzoom_forge_1.0.1-1_MC_1.19.jar"
"kleeslabs-forge-1.19-12.1.0.jar"
"onkrete_forge_1.5.0_MC_1.19-1.19.1.jar"
"kotlinforforge-3.7.1-obf.jar"
"LibX-1.19.2-4.2.6.jar"
"luggage-1.5.jar"
"matc-1.3.0.jar"
"mavm-1.1.0-mc1.19.jar"
"mcjtylib-1.19-7.0.2.jar"
"Mekanism-1.19.2-10.3.3.470.jar"
"MekanismAdditions-1.19.2-10.3.3.470.jar"
"MekanismGenerators-1.19.2-10.3.3.470.jar"
"MekanismTools-1.19.2-10.3.3.470.jar"
"mob_grinding_utils-1.19-0.4.44.jar"
"moonlight-1.19.2-2.0.27.jar"
"morevillagers-forge-1.19-4.0.3.jar"
"MysticalAgradditions-1.19.1-6.0.0.jar"
"MysticalAgriculture-1.19.2-6.0.1.jar"
"namepain-1.4.1 forge-1.19.x.jar"
"naturalist-forge-2.1.1-1.19.2.jar"
"NaturesCompass-1.19.2-1.9.7-forge.jar"
"notenoughanimations-forge-1.6.1-mc1.19.1.jar"
"notenoughcrashes-4.1.8+1.19.2-forge.jar"
"oculus-mc1.19.2-1.2.8.jar"
"OfflineSkins-1.19.2-v1.jar"
"Paintings-forge-1.19.2-10.2.0.0.jar"
"Patchouli-1.19.2-76.jar"
"PigPen-Forge-1.19.2-11.1.2.jar"
"pipez-1.19.2-1.0.0.jar"
"plaingrinder-1.19-1.2.6.jar"
"polymorph-forge-0.45.0+1.19.2.jar"
"ProjectE-1.19.2-PE1.0.1B.jar"
"PuzzlesLib-v4.3.1-1.19.2-Forge.jar"
"repurposed_structures_forge-6.2.2+1.19.2.jar"
"Rex's-AdditionalStructures-1.19-(v.4.0.1).jar"
"RoughlyEnoughItems-9.1.530.jar"
"Runelic-Forge-1.19.2-14.1.2.jar"
"savage_and_ravage-1.19-5.0.2.jar"
"shetiphiancore-1.19-3.11.0.jar"
"snad-1.3.1.jar"
"spirit-forge-1.19.2-2.1.12.jar"
"Structory-1.19-1.2.jar"
"structure_gel-1.19.2-2.6.1.jar"
"supermartijn642configlib-1.1.6b-forge-mc1.19.jar"
"supermartijn642corelib-1.0.19a-forge-mc1.19.jar"
"Thatched-forge-1.19.2-1.2.0.jar"
"thedragonlib-1.19-1.0.0.jar"
"transparent-5.1.0+1.19-forge.jar"
"trashslot-forge-1.19-12.0.0.jar"
"twilightforest-1.19-4.2.1392-universal.jar"
"vanilla_degus-1.19-v1.3.1-forge.jar"
"villagertools-1.19-1.0.3.jar"
"Waddles-1.19-0.9.1.jar"
"ZeroCore2-1.19-2.1.25.jar"
"absentbydesign-1.19-1.7.0.jar"
"additionaladditions-5.0.2.jar"
"Adorn-3.6.1+1.19-forge.jar"
"advancednetherite-1.13.7-1.19.2.jar"
"AEInfinityBooster-1.19.2-1.2.0+11.jar"
"AI-Improvements-1.19-0.5.1.jar"
"alexsmobs-1.19.5.jar"
"Amplified_Nether_v1.2.jar"

Attached here is also my latest log
[latest.log](https://github.com/jrbudda/minecrift/files/9570646/latest.log)
This was off of a fresh install of NonVR Vivecraft (Trying to make sure the mods work before going into VR)

**Comment by longlongCODE** [comment]
收到邮件了，但是如果邮件很重要还请你发一条短信通知我收信。号码18817566090    谢谢

**Comment by fayer3** [comment]
first this is the wrong repo, this is for 1.7.10
second, oculus is not compatible with this version of vivecraft, so remove that

**Comment by Varrick1** [comment]
Aw beans sorry--I'll look into that though thanks!

> first this is the wrong repo, this is for 1.7.10 second, oculus is not compatible with this version of vivecraft, so remove that
