### ISSUE TITLE
Enable non-VR players to use this plugin so they can play with VR players

### ISSUE THREAD

**Issue by timcharper** [jrbudda/minecrift#35]
I've installed the latest JDK and SteamVR. This mod works perfectly on my VR computer; however, running on my macbook (in bootcamp) I'm unable to start the game with the plugin so I can join the VR player.

```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 6/3/16 8:12 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at com.mtbs3d.minecrift.provider.MCOpenVR.setKeyboardOverlayShowing(MCOpenVR.java:497)
    at net.minecraft.client.gui.GuiTextField.func_146195_b(GuiTextField.java:689)
    at net.minecraft.client.gui.GuiCreateWorld.func_73866_w_(GuiCreateWorld.java:78)
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:344)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1217)
    at net.minecraft.client.gui.GuiSelectWorld.func_146284_a(GuiSelectWorld.java:134)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:291)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:422)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:377)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2315)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1408)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1316)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at com.mtbs3d.minecrift.provider.MCOpenVR.setKeyboardOverlayShowing(MCOpenVR.java:497)
    at net.minecraft.client.gui.GuiTextField.func_146195_b(GuiTextField.java:689)
    at net.minecraft.client.gui.GuiCreateWorld.func_73866_w_(GuiCreateWorld.java:78)
    at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:344)
    at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1217)
    at net.minecraft.client.gui.GuiSelectWorld.func_146284_a(GuiSelectWorld.java:134)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:291)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:422)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:377)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.GuiCreateWorld
Stacktrace:
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2315)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1408)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:1316)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 214115744 bytes (204 MB) / 450289664 bytes (429 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D1 3 mods loaded, 3 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJA  Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3345' Renderer: 'Intel(R) Iris(TM) Pro Graphics 5200'
    Launched Version: vivecraft-1.7.10-Vivecraft-jrbudda14-forge-nohydra
    LWJGL: 2.9.1
    OpenGL: Intel(R) Iris(TM) Pro Graphics 5200 GL version 4.2.0 - Build 10.18.10.3345, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: On (16)
    OptiFine Version: OptiFine_1.7.10_HD_U_D1
    Render Distance Chunks: 8
    Mipmaps: 4
    Anisotropic Filtering: 16
    Antialiasing: 0
    Multitexture: false
    OpenGlVersion: 4.2.0 - Build 10.18.10.3345
    OpenGlRenderer: Intel(R) Iris(TM) Pro Graphics 5200
    OpenGlVendor: Intel
    CpuCount: 8
```

**Comment by fazo96** [comment]
As far as I know, VR players can join regular non-modded servers but teleport won't work. I don't know about using a non-modded client to join a VR server, but it should work because I read somewhere on reddit that someone did it.

In other words, have you tried joining your friend's server without modding your client?

**Comment by possi** [comment]
At the current state the MP Protocol isn't touched, so you're able to play on a Regular 1.7.10 Server and every regular 1.7.10 client can join your LAN game.

Just create a new Profile in the Minecraft Launcher and edit the "Use version" to "release 1.7.10".

**Comment by timcharper** [comment]
Thanks for the responses! I'd read that multiplayer could work with all of the VR features (teleportation locomotion) in tact as long as everyone installed the software. Turns out you can also keep teleportation on if you turn down the "moved wrongly" tolerance... which I accomplished by following this tutorial:

https://www.reddit.com/r/Vive/comments/4hbo45/setup_your_minecraftserver_spigot_bukkit_17_with/

**Comment by fucnknown** [comment]
Tim, next time check the wiki: https://www.reddit.com/r/Vive/wiki/minecrift_for_vive
If you have something useful to add to it later , don't be afraid to add

**Comment by timcharper** [comment]
Wonderful! Thanks, @ziggrrauglurr . I wasn't aware of that page. Probably because I didn't RTFM.
